name: Test and Validate

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with ruff (if available)
      run: |
        pip install ruff
        ruff check . --fix
      continue-on-error: true
    
    - name: Type check with mypy (if available)
      run: |
        pip install mypy
        mypy aibot.py main.py --ignore-missing-imports
      continue-on-error: true
    
    - name: Test imports and basic syntax
      run: |
        python -c "import aibot; print('✅ aibot.py imports successfully')"
        python -c "import main; print('✅ main.py imports successfully')"
        python -m py_compile aibot.py main.py
        echo "✅ All Python files compile successfully"
    
    - name: Validate Docker build
      run: |
        echo "🐳 Testing Docker build..."
        docker build -t test-image .
        echo "✅ Docker build successful"
    
    - name: Security scan with bandit (if available)
      run: |
        pip install bandit
        bandit -r . -f json -o bandit-report.json
        echo "✅ Security scan completed"
      continue-on-error: true
    
    - name: Check for secrets in code
      run: |
        echo "🔍 Checking for potential secrets..."
        if grep -r -E "(sk-|xoxb-|xapp-|ghp_)" --include="*.py" --include="*.sh" --exclude-dir=".github" .; then
          echo "❌ Potential secrets found in code!"
          exit 1
        else
          echo "✅ No secrets found in code"
        fi
    
    - name: Test deployment script syntax
      run: |
        echo "🧪 Testing deployment script..."
        bash -n deploy.sh
        bash -n setup-github-actions.sh
        bash -n setup-project.sh
        echo "✅ All shell scripts have valid syntax"